services:
  db:
    image: postgres:15
    container_name: coffee_postgres
    restart: always
    environment:
      POSTGRES_USER: coffee_admin
      POSTGRES_PASSWORD: coffee_password
      POSTGRES_DB: coffee_shop
    ports:
      - "5440:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Optional: PGAdmin to visualize your database at http://localhost:5050
  pgadmin:
    image: dpage/pgadmin4
    container_name: coffee_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@coffee.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
